In [ ]:
print("Welcome to Data Analytics and Visualization")

Welcome to Data Analytics and Visualization

In [ ]:
import numpy as np
marks= np.array([78,85,94,96,90])
print("Marks:", marks)
print("Type:",type(marks))

Marks: [78 85 94 96 90]
Type: <class 'numpy.ndarray'>

In [ ]:
print("Number of dimensions:", marks.ndim)
print("Shape:", marks.shape)
print("Number of elements:", marks.size)

Number of dimensions: 1
Shape: (5,)
Number of elements: 5

In [ ]:
marks= np.array([78,85,94,96,90])
print("Original Marks:", marks)
print("Add 5:", marks+5)
print("Multiply by 2:", marks*2)
print("Divide by 2:", marks/2)
print("Square:", marks**2)

Original Marks: [78 85 94 96 90]
Add 5: [ 83  90  99 101  95]
Multiply by 2: [156 170 188 192 180]
Divide by 2: [39.  42.5 47.  48.  45. ]
Square: [6084 7225 8836 9216 8100]

In [ ]:
print("Sum:", marks.sum())
print("Mean:", marks.mean())
print("Maximun:", marks.max())
print("Minimun:", marks.min())

Sum: 443
Mean: 88.6
Maximun: 96
Minimun: 78

In [ ]:
print("First mark:", marks[0])
print("Second mark:", marks[1])
print("Last mark:", marks[-1])

First mark: 78
Second mark: 85
Last mark: 90

In [ ]:
print("Index 1 to 3:", marks[1:4])
print("First three:", marks[:3])
print("From index 2:", marks[2:])
print("Every second element:", marks[ : :2])

Index 1 to 3: [85 94 96]
First three: [78 85 94]
From index 2: [94 96 90]
Every second element: [78 94 90]

In [ ]:
student_marks= np.array([[78,85,92],
                        [67,88,76],
                        [90,95,89]])
print(student_marks)
print("Shape:", student_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)

In [ ]:
print("Mean of all values:", student_marks.mean())
print("Column-wise mean:", student_marks.mean(axis=0))
print("Row-wise mean:", student_marks.mean(axis=1))

Mean of all values: 84.44444444444444
Column-wise mean: [78.33333333 89.33333333 85.66666667]
Row-wise mean: [85.         77.         91.33333333]

In [ ]:
import pandas as pd
data= {"Name": ["Anu", "Rahul","Kiran","Priya"],
      "Branch" : ["CSE", "AIML","CSE", "AIML"],
      "Marks" : [85,91,76,88]}
df=pd.DataFrame(data)
df

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)

Shape: (4, 3)

Columns:
Index(['Name', 'Branch', 'Marks'], dtype='object')

In [ ]:
df.head()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.tail()

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe()

           Marks
count   4.000000
mean   85.000000
std     6.480741
min    76.000000
25%    82.750000
50%    86.500000
75%    88.750000
max    91.000000

In [ ]:
print("Marks column:")
print(df["Marks"])
print("\n Branch and Marks:")
print(df[["Branch", "Marks"]])

Marks column:
0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

 Branch and Marks:
  Branch  Marks
0    CSE     85
1   AIML     91
2    CSE     76
3   AIML     88

In [ ]:
print("First row:")
print(df.iloc[0])
print("\nSecond row:")
print(df.iloc[1])
print("\nFirst three rows:")
print(df.iloc[0:3])

First row:
Name      Anu
Branch    CSE
Marks      85
Name: 0, dtype: object

Second row:
Name      Rahul
Branch     AIML
Marks        91
Name: 1, dtype: object

First three rows:
    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

In [ ]:
print("First two rows and first two columns:")
print(df.iloc[0:2,0:2])

First two rows and first two columns:
    Name Branch
0    Anu    CSE
1  Rahul   AIML

In [ ]:
print("First three rows:")
display(df.iloc[0:3])
print("Rows 1 to 3, Name and Marks:")
print(df.iloc[1:4,0:3])

First three rows:

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
2  Kiran    CSE     76

Rows 1 to 3, Name and Marks:
    Name Branch  Marks
1  Rahul   AIML     91
2  Kiran    CSE     76
3  Priya   AIML     88

In [ ]:
high_scores=df[df["Marks"]>90]
high_scores

    Name Branch  Marks
1  Rahul   AIML     91

In [ ]:
print("Students from CSE:")
display(df[df["Branch"] == "CSE"])

Students from CSE:

    Name Branch  Marks
0    Anu    CSE     85
2  Kiran    CSE     76

In [ ]:
print("Students scoring 85 or above:")
display(df[df["Marks"]>=85])

Students scoring 85 or above:

    Name Branch  Marks
0    Anu    CSE     85
1  Rahul   AIML     91
3  Priya   AIML     88

In [ ]:
data={"Name":["Asha","Bharat","Chetan","Divya","Esha"],
      "Department":["CSE","ISE","CSE","AIML","ISE"],
      "Marks":[72,91,84,95,68],
      "Attendance":[82,94,88,96,79]}
students=pd.DataFrame(data)
students

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96
4    Esha        ISE     68          79

In [ ]:
display(students.iloc[ : ,0:3:2])

     Name  Marks
0    Asha     72
1  Bharat     91
2  Chetan     84
3   Divya     95
4    Esha     68

In [ ]:
display(students[students["Marks"]>80])

     Name Department  Marks  Attendance
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96

In [ ]:
display(students[students["Attendance"]>85])

     Name Department  Marks  Attendance
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96

In [ ]:
print(students.iloc[0:3])

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88

In [ ]:
print(students["Marks"].mean())

82.0

In [ ]:
print("Max marks:", students["Marks"].max)

Max marks: <bound method Series.max of 0    72
1    91
2    84
3    95
4    68
Name: Marks, dtype: int64>

In [ ]:
print("Students from CSE:")
display(students[students["Department"] == "CSE"])

Students from CSE:

     Name Department  Marks  Attendance
0    Asha        CSE     72          82
2  Chetan        CSE     84          88

In [ ]:
print("Students whose marks are atleat 80 and attendance is greater than 85")
display(students[(students["Marks"]>=80) & (students["Attendance"]>85)])

Students whose marks are atleat 80 and attendance is greater than 85

     Name Department  Marks  Attendance
1  Bharat        ISE     91          94
2  Chetan        CSE     84          88
3   Divya       AIML     95          96